Added sprites graphic
"AttributeError: 'Goomba' object has no attribute 'jumping'" error still
present (only occurs sometimes when game starts)
Added graphics for goombas, bullets and the player.
Removed shrink and grow blocks from map2 to prevent bugs because of the
player skin